sudo: required
services:
    - docker

    before_install: 
        - docker build -t 5midpark/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 5midpark/react-test npm test -- --coverage

after_success: 
    - docker build -t 5midpark/multi-client ./client
    - docker build -t 5midpark/multi-nginx ./nginx
    - docker build -t 5midpark/multi-server ./server
    - docker build -t 5midpark/multi-worker ./worker

# Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to Docker Hub
    - docker push 5midpark/multi-client
    - docker push 5midpark/multi-nginx
    - docker push 5midpark/multi-server
    - docker push 5midpark/multi-worker